// app/sitemap.js
export default function sitemap() {
  return [
    // Homepage
    {
      url: 'https://www.teksacademy.com',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1.0,
    },
    // Courses
    {
      url: 'https://www.teksacademy.com/courses',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-full-stack-python-development-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-full-stack-java-development-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-data-science-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-awsplusdevops-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-digital-marketing-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-data-analytics-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-multimedia-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-bim-building-information-modeling-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-sap-fico-finance-and-controlling-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-medical-coding-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-testingtools-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-advance-excel-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-autocad-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-revit-mep-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-business-analytics-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-generative-ai-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-sapmm-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: 'https://www.teksacademy.com/courses/best-cyber-security-course-training-institute',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    // Branches
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-ameerpet',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-hiteccity',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-secunderabad',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-dilsukhnagar',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-mehdipatnam',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-kukatpally',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-bangalore',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-visakhapatnam',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/branch/best-software-training-institute-kompally',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    // Success Stories & Resources
    {
      url: 'https://www.teksacademy.com/success-stories',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/resources/ebook',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/resources/interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    // Interview Questions
    {
      url: 'https://www.teksacademy.com/interview-questions/python-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/java-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/data-science-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/digital-marketing-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/aws-dev-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/bim-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/software-testing-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/sap-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/multimedia-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/medical-coding-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/advanced-excel-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/auto-cad-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/revit-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/data-analytics-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/sap-mm-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/cyber-security-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/generative-ai-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/interview-questions/business-analytics-interview-questions',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    // Discover Pages
    {
      url: 'https://www.teksacademy.com/discover/about-us',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/discover/gallery',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/discover/media',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/discover/contact-us',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/discover/support',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    // Placements
    {
      url: 'https://www.teksacademy.com/placements/alumni',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/placements/recruiters',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.teksacademy.com/apply-for-jobs',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    // Blogs
    {
      url: 'https://www.teksacademy.com/blogs',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
  ];
}